# Site settings
title: Four Seasons Blog  #你博客的标题
SEOTitle: 四季映画的博客 | FourSeasons Blog  #显示在浏览器上搜索的时候显示的标题
header-img: img/page-bg-keyboard.png #显示在首页的背景图片
email: 379663282@qq.com
description: "Hey，我是四季，一名从土木工程转行的程序猿,这是我的利用 GitHub Pages 与 Jekyll 搭建的个人博客（当然是fork的大神的啦）。欢迎大家来玩。" #网站介绍
keyword: "大数据,GitHub,博客,Blog,JAVA" #关键词
url: "https://iteh3712198.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "blog" # you code repository
author: Tao

# 是否托管在Coding_Pages
Coding_Pages: true

#  是否开启百度自动推送JS代码
baidu_js_push: false

# Sidebar settings侧边栏
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "虚拟体验也好，梦也罢，这个世上的信息，既现实也虚幻;无论如何，人一生所能接触的事物也只是沧海一粟"
sidebar-avatar: /img/avatar_p11179162.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings社交账号
RSS: false
# weibo_username:
github_username:    iteh3712198
# facebook_username:
# coding_username: fedemo



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 'd6f4e78cd88787a1e5da'    #生成的clientID
  clientSecret: '8d2376a030760b36d0d18b192d008592d7481a00'   #同上
  repo: img_gitalk    #仓库名称
  owner: iteh3712198    #github用户名
  admin: iteh3712198




# Analytics settings 百度统计track_id
# Baidu Analytics
ba_track_id: 5a65bc7eb12a4f6c3548ab3189cb5884
             

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

#search plugins
search: true                            # 是否使用搜索插件

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends好友链接
friends: [
    {
        title: "Fe Blog",
        href: "https://fedemo.top/"
    },{
        title: "interview",
        href: "https://fedemo.github.io/interview/"
    },{
        title: "Fe Coding",
        href: "https://coding.net/u/fedemo/project"
    },{
        title: "BY Blog",
        href: "http://qiubaiying.top/"
    }
]
